/******************************************************************************
 * Copyright (c) 2013, AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alljoyn_services_audio_sink_BusHandler */

#ifndef _Included_org_alljoyn_services_audio_sink_BusHandler
#define _Included_org_alljoyn_services_audio_sink_BusHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef org_alljoyn_services_audio_sink_BusHandler_INITIALIZE
#define org_alljoyn_services_audio_sink_BusHandler_INITIALIZE 0L
#undef org_alljoyn_services_audio_sink_BusHandler_SHUTDOWN
#define org_alljoyn_services_audio_sink_BusHandler_SHUTDOWN 10L
/*
 * Class:     org_alljoyn_services_audio_sink_BusHandler
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_services_audio_sink_BusHandler_initialize
    (JNIEnv *, jobject, jstring);

/*
 * Class:     org_alljoyn_services_audio_sink_BusHandler
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_alljoyn_services_audio_sink_BusHandler_shutdown
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
