# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('samples_env')

# Platform specific libraries
if samples_env['OS_GROUP'] == 'posix':
    samples_env.Append(LIBS = ['asound'])

# Sample programs
progs = [
    samples_env.Program('SinkClient',  ['SinkClient.cc']),
    samples_env.Program('SinkService',  ['SinkService.cc']),
    ]

if samples_env['OS'] != 'android':
    samples_env.Install('$AUDIO_DISTDIR/bin/samples', progs)
    samples_env.Install('$AUDIO_DISTDIR/samples', samples_env.Glob('*.cc'))
    samples_env.Install('$AUDIO_DISTDIR/samples', 'README.txt')
